replicaCount: 2

image:
  repository: todo-app
  tag: "v1"
  pullPolicy: Never

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

httpRoute:
  enabled: false
